// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.ampdev.protos;

public final class FeedInputProtos {
  private FeedInputProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FeedInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ampdev.protos.FeedInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 1;</code>
     */
    int getUserId();

    /**
     * <code>required int32 categoryId = 2;</code>
     */
    boolean hasCategoryId();
    /**
     * <code>required int32 categoryId = 2;</code>
     */
    int getCategoryId();

    /**
     * <code>required int32 newspaperId = 3;</code>
     */
    boolean hasNewspaperId();
    /**
     * <code>required int32 newspaperId = 3;</code>
     */
    int getNewspaperId();

    /**
     * <code>required string rssFeedUrl = 4;</code>
     */
    boolean hasRssFeedUrl();
    /**
     * <code>required string rssFeedUrl = 4;</code>
     */
    java.lang.String getRssFeedUrl();
    /**
     * <code>required string rssFeedUrl = 4;</code>
     */
    com.google.protobuf.ByteString
        getRssFeedUrlBytes();

    /**
     * <code>optional int32 subcategoryId = 5;</code>
     */
    boolean hasSubcategoryId();
    /**
     * <code>optional int32 subcategoryId = 5;</code>
     */
    int getSubcategoryId();
  }
  /**
   * Protobuf type {@code com.ampdev.protos.FeedInput}
   */
  public static final class FeedInput extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ampdev.protos.FeedInput)
      FeedInputOrBuilder {
    // Use FeedInput.newBuilder() to construct.
    private FeedInput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FeedInput(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FeedInput defaultInstance;
    public static FeedInput getDefaultInstance() {
      return defaultInstance;
    }

    public FeedInput getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FeedInput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              categoryId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              newspaperId_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              rssFeedUrl_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              subcategoryId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ampdev.protos.FeedInputProtos.internal_static_com_ampdev_protos_FeedInput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ampdev.protos.FeedInputProtos.internal_static_com_ampdev_protos_FeedInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ampdev.protos.FeedInputProtos.FeedInput.class, com.ampdev.protos.FeedInputProtos.FeedInput.Builder.class);
    }

    public static com.google.protobuf.Parser<FeedInput> PARSER =
        new com.google.protobuf.AbstractParser<FeedInput>() {
      public FeedInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeedInput(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FeedInput> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required int32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int CATEGORYID_FIELD_NUMBER = 2;
    private int categoryId_;
    /**
     * <code>required int32 categoryId = 2;</code>
     */
    public boolean hasCategoryId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 categoryId = 2;</code>
     */
    public int getCategoryId() {
      return categoryId_;
    }

    public static final int NEWSPAPERID_FIELD_NUMBER = 3;
    private int newspaperId_;
    /**
     * <code>required int32 newspaperId = 3;</code>
     */
    public boolean hasNewspaperId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 newspaperId = 3;</code>
     */
    public int getNewspaperId() {
      return newspaperId_;
    }

    public static final int RSSFEEDURL_FIELD_NUMBER = 4;
    private java.lang.Object rssFeedUrl_;
    /**
     * <code>required string rssFeedUrl = 4;</code>
     */
    public boolean hasRssFeedUrl() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string rssFeedUrl = 4;</code>
     */
    public java.lang.String getRssFeedUrl() {
      java.lang.Object ref = rssFeedUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rssFeedUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string rssFeedUrl = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRssFeedUrlBytes() {
      java.lang.Object ref = rssFeedUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rssFeedUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBCATEGORYID_FIELD_NUMBER = 5;
    private int subcategoryId_;
    /**
     * <code>optional int32 subcategoryId = 5;</code>
     */
    public boolean hasSubcategoryId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 subcategoryId = 5;</code>
     */
    public int getSubcategoryId() {
      return subcategoryId_;
    }

    private void initFields() {
      userId_ = 0;
      categoryId_ = 0;
      newspaperId_ = 0;
      rssFeedUrl_ = "";
      subcategoryId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCategoryId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNewspaperId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRssFeedUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, categoryId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, newspaperId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getRssFeedUrlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, subcategoryId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, categoryId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, newspaperId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getRssFeedUrlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, subcategoryId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ampdev.protos.FeedInputProtos.FeedInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ampdev.protos.FeedInputProtos.FeedInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ampdev.protos.FeedInputProtos.FeedInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ampdev.protos.FeedInputProtos.FeedInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ampdev.protos.FeedInputProtos.FeedInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ampdev.protos.FeedInputProtos.FeedInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ampdev.protos.FeedInputProtos.FeedInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ampdev.protos.FeedInputProtos.FeedInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ampdev.protos.FeedInputProtos.FeedInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ampdev.protos.FeedInputProtos.FeedInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ampdev.protos.FeedInputProtos.FeedInput prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ampdev.protos.FeedInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ampdev.protos.FeedInput)
        com.ampdev.protos.FeedInputProtos.FeedInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ampdev.protos.FeedInputProtos.internal_static_com_ampdev_protos_FeedInput_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ampdev.protos.FeedInputProtos.internal_static_com_ampdev_protos_FeedInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ampdev.protos.FeedInputProtos.FeedInput.class, com.ampdev.protos.FeedInputProtos.FeedInput.Builder.class);
      }

      // Construct using com.ampdev.protos.FeedInputProtos.FeedInput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        categoryId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        newspaperId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        rssFeedUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        subcategoryId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ampdev.protos.FeedInputProtos.internal_static_com_ampdev_protos_FeedInput_descriptor;
      }

      public com.ampdev.protos.FeedInputProtos.FeedInput getDefaultInstanceForType() {
        return com.ampdev.protos.FeedInputProtos.FeedInput.getDefaultInstance();
      }

      public com.ampdev.protos.FeedInputProtos.FeedInput build() {
        com.ampdev.protos.FeedInputProtos.FeedInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ampdev.protos.FeedInputProtos.FeedInput buildPartial() {
        com.ampdev.protos.FeedInputProtos.FeedInput result = new com.ampdev.protos.FeedInputProtos.FeedInput(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.categoryId_ = categoryId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.newspaperId_ = newspaperId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.rssFeedUrl_ = rssFeedUrl_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.subcategoryId_ = subcategoryId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ampdev.protos.FeedInputProtos.FeedInput) {
          return mergeFrom((com.ampdev.protos.FeedInputProtos.FeedInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ampdev.protos.FeedInputProtos.FeedInput other) {
        if (other == com.ampdev.protos.FeedInputProtos.FeedInput.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasCategoryId()) {
          setCategoryId(other.getCategoryId());
        }
        if (other.hasNewspaperId()) {
          setNewspaperId(other.getNewspaperId());
        }
        if (other.hasRssFeedUrl()) {
          bitField0_ |= 0x00000008;
          rssFeedUrl_ = other.rssFeedUrl_;
          onChanged();
        }
        if (other.hasSubcategoryId()) {
          setSubcategoryId(other.getSubcategoryId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasCategoryId()) {
          
          return false;
        }
        if (!hasNewspaperId()) {
          
          return false;
        }
        if (!hasRssFeedUrl()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ampdev.protos.FeedInputProtos.FeedInput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ampdev.protos.FeedInputProtos.FeedInput) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <code>required int32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      private int categoryId_ ;
      /**
       * <code>required int32 categoryId = 2;</code>
       */
      public boolean hasCategoryId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 categoryId = 2;</code>
       */
      public int getCategoryId() {
        return categoryId_;
      }
      /**
       * <code>required int32 categoryId = 2;</code>
       */
      public Builder setCategoryId(int value) {
        bitField0_ |= 0x00000002;
        categoryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 categoryId = 2;</code>
       */
      public Builder clearCategoryId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        categoryId_ = 0;
        onChanged();
        return this;
      }

      private int newspaperId_ ;
      /**
       * <code>required int32 newspaperId = 3;</code>
       */
      public boolean hasNewspaperId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 newspaperId = 3;</code>
       */
      public int getNewspaperId() {
        return newspaperId_;
      }
      /**
       * <code>required int32 newspaperId = 3;</code>
       */
      public Builder setNewspaperId(int value) {
        bitField0_ |= 0x00000004;
        newspaperId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 newspaperId = 3;</code>
       */
      public Builder clearNewspaperId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        newspaperId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object rssFeedUrl_ = "";
      /**
       * <code>required string rssFeedUrl = 4;</code>
       */
      public boolean hasRssFeedUrl() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string rssFeedUrl = 4;</code>
       */
      public java.lang.String getRssFeedUrl() {
        java.lang.Object ref = rssFeedUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            rssFeedUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string rssFeedUrl = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRssFeedUrlBytes() {
        java.lang.Object ref = rssFeedUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rssFeedUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string rssFeedUrl = 4;</code>
       */
      public Builder setRssFeedUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        rssFeedUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string rssFeedUrl = 4;</code>
       */
      public Builder clearRssFeedUrl() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rssFeedUrl_ = getDefaultInstance().getRssFeedUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string rssFeedUrl = 4;</code>
       */
      public Builder setRssFeedUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        rssFeedUrl_ = value;
        onChanged();
        return this;
      }

      private int subcategoryId_ ;
      /**
       * <code>optional int32 subcategoryId = 5;</code>
       */
      public boolean hasSubcategoryId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 subcategoryId = 5;</code>
       */
      public int getSubcategoryId() {
        return subcategoryId_;
      }
      /**
       * <code>optional int32 subcategoryId = 5;</code>
       */
      public Builder setSubcategoryId(int value) {
        bitField0_ |= 0x00000010;
        subcategoryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 subcategoryId = 5;</code>
       */
      public Builder clearSubcategoryId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        subcategoryId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.ampdev.protos.FeedInput)
    }

    static {
      defaultInstance = new FeedInput(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ampdev.protos.FeedInput)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ampdev_protos_FeedInput_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ampdev_protos_FeedInput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\022\021com.ampdev.protos\"o\n\tFeed" +
      "Input\022\016\n\006userId\030\001 \002(\005\022\022\n\ncategoryId\030\002 \002(" +
      "\005\022\023\n\013newspaperId\030\003 \002(\005\022\022\n\nrssFeedUrl\030\004 \002" +
      "(\t\022\025\n\rsubcategoryId\030\005 \001(\005B$\n\021com.ampdev." +
      "protosB\017FeedInputProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ampdev_protos_FeedInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ampdev_protos_FeedInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ampdev_protos_FeedInput_descriptor,
        new java.lang.String[] { "UserId", "CategoryId", "NewspaperId", "RssFeedUrl", "SubcategoryId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
